// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdqfdrpdo4sAI1IQnzVORYAa2IVRMduDg',
    appId: '1:398776786354:web:d90ad25b79d3d57f57d8ab',
    messagingSenderId: '398776786354',
    projectId: 'task-list-flutter-3f21d',
    authDomain: 'task-list-flutter-3f21d.firebaseapp.com',
    storageBucket: 'task-list-flutter-3f21d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQrmJMR2QA1fO4c4j-DobAxjihCgqe2l4',
    appId: '1:398776786354:android:d0e098a3ba190b2357d8ab',
    messagingSenderId: '398776786354',
    projectId: 'task-list-flutter-3f21d',
    storageBucket: 'task-list-flutter-3f21d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-amIB74n9ZSQv_9BOcZ5buhroNPzMBo',
    appId: '1:398776786354:ios:b5032cdd19dc874657d8ab',
    messagingSenderId: '398776786354',
    projectId: 'task-list-flutter-3f21d',
    storageBucket: 'task-list-flutter-3f21d.appspot.com',
    iosClientId: '398776786354-vtsdcrcicc7lmp5dui800b7qi1ajqdat.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs-amIB74n9ZSQv_9BOcZ5buhroNPzMBo',
    appId: '1:398776786354:ios:b5032cdd19dc874657d8ab',
    messagingSenderId: '398776786354',
    projectId: 'task-list-flutter-3f21d',
    storageBucket: 'task-list-flutter-3f21d.appspot.com',
    iosClientId: '398776786354-vtsdcrcicc7lmp5dui800b7qi1ajqdat.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskList',
  );
}
